import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const base=new URL('.',import.meta.url);
const groups=JSON.parse(await readFile(new URL('catalogo.json',base),'utf8'));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses={G:['g','✓','Adequado'],Y:['y','~','Condicional'],R:['r','×','Não oferece diretamente']};
const labels=['Recurso e demonstração','Facilidade de criação','Apresentação de informações','Prática e feedback','Avaliação da aprendizagem','Taxonomia de Bloom: possibilidades','Exemplo pedagógico'];
function statusCell(s,label){const [code,...text]=s.split('|');const [css,symbol,name]=statuses[code];return `<td data-label="${escape(label)}"><span class="badge ${css}"><span aria-hidden="true">${symbol}</span> ${name}</span><p>${escape(text.join('|'))}</p></td>`;}
function row(item){const [name,pt,url,ease,setup,info,practice,assessment,bloom,example,image]=item;const icon=image?`<img class="resource-icon" src="${escape(image)}" alt="" width="48" height="48" loading="lazy">`:'';return `<tr><th scope="row"><a href="${escape(url)}">${icon}${escape(pt)}</a><small>${escape(name)}</small></th><td data-label="Facilidade de criação"><strong>${escape(ease)}</strong><p>${escape(setup)}</p></td>${statusCell(info,labels[2])}${statusCell(practice,labels[3])}${statusCell(assessment,labels[4])}<td class="plain" data-label="Taxonomia de Bloom: possibilidades"><span>${escape(bloom)}</span></td><td class="plain" data-label="Exemplo pedagógico"><span>${escape(example)}</span>${name==='Accordion'?'<p><a href="atividades/accordion.html">Experimentar exemplo: Piaget, Vigotski e Wallon</a></p>':name==='Image Hotspots'?'<p><a href="atividades/image-hotspots.html">Experimentar exemplo: segurança do trabalho</a></p>':''}</td></tr>`;}
const notes={praticar:'Dialog Cards revela o verso do cartão. Flashcards solicita uma resposta digitada e verifica sua correção.',questoes:'No Summary, o estudante seleciona afirmações preparadas pelo professor para compor uma síntese. A verificação depende das respostas previamente configuradas.',decisoes:'Branching Scenario organiza decisões e desfechos; Virtual Tour conecta ambientes; Game Map organiza etapas com conteúdos H5P e regras de avanço.'};
const sections=groups.map((g,i)=>`<section class="guide-group" id="${g.id}" aria-labelledby="title-${g.id}"><details class="group-disclosure" open><summary class="group-title"><span class="number" aria-hidden="true">${i+1}</span><h2 id="title-${g.id}">${escape(g.title)}</h2><span class="count">${g.items.length} recursos</span></summary><p class="group-intro">${escape(g.intro)}</p><div class="table-wrap" tabindex="0" role="region" aria-label="Tabela: ${escape(g.title)}"><table><caption>Comparação dos recursos H5P para ${escape(g.title.toLowerCase())}</caption><thead><tr>${labels.map(l=>`<th scope="col">${escape(l)}</th>`).join('')}</tr></thead><tbody>${g.items.map(row).join('')}</tbody></table></div>${notes[g.id]?`<aside class="reading-note"><p>${escape(notes[g.id])}</p></aside>`:''}</details></section>`).join('\n');
const html=`<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Compare 54 recursos H5P por objetivo pedagógico, facilidade de criação, prática, avaliação e possibilidades da Taxonomia de Bloom."><meta name="theme-color" content="#357E4B"><title>Guia de Funcionalidades H5P para Professores e Educadores</title><link rel="icon" type="image/png" href="images/favicon-ifce.png?v=1"><link rel="stylesheet" href="styles.css?v=8"><script src="guide.js?v=1" defer></script></head><body>
<a class="skip" href="#conteudo">Ir para o conteúdo</a><header><div class="shell header-layout"><a class="institution-logo" href="https://portal.ifce.edu.br/"><img src="images/ifce-logo-vertical.svg" alt="IFCE — Instituto Federal do Ceará"></a><div class="header-copy"><p class="eyebrow">54 recursos · 4 objetivos pedagógicos</p><h1>Guia de Funcionalidades H5P</h1><p>Para professores e educadores: compare os recursos e escolha a interação que ajuda o estudante a alcançar seu objetivo de aprendizagem.</p></div></div></header>
<nav aria-label="Grupos de recursos"><div class="shell navlinks">${groups.map((g,i)=>`<a href="#${g.id}">${i+1}. ${escape(g.title)}</a>`).join('')}</div></nav>
<main id="conteudo" class="shell"><div class="intro"><div><p><strong>Comece pelo objetivo de aprendizagem.</strong> Os grupos indicam a finalidade predominante; um recurso pode atender a vários objetivos.</p><p>Selecione o nome de um recurso para abrir sua página oficial com descrição e demonstrações.</p></div></div>
<section class="reading-guide" aria-labelledby="como-ler"><h2 id="como-ler">Como ler este guia</h2><p>As classificações ajudam a identificar como cada recurso pode contribuir para seu objetivo pedagógico.</p><div class="classification-cards"><div class="classification-card g"><h3><span aria-hidden="true">✓</span> Adequado</h3><p>Oferece funcionalidades diretamente relacionadas ao objetivo, conforme as condições descritas na tabela.</p></div><div class="classification-card y"><h3><span aria-hidden="true">~</span> Condicional</h3><p>Pode atender ao objetivo, mas depende de atividades específicas, orientação do professor ou complementação.</p></div><div class="classification-card r"><h3><span aria-hidden="true">×</span> Não oferece diretamente</h3><p>Precisa ser combinado com outra ferramenta ou atividade para atender ao objetivo.</p></div></div><p class="classification-note">A classificação indica a adequação ao objetivo, não a qualidade do recurso. A aprendizagem depende do planejamento e da tarefa proposta.</p></section>
${sections}
<section class="notes" aria-labelledby="orientacoes"><h2 id="orientacoes">Como interpretar o guia</h2><ol><li><strong>Facilidade de criação:</strong> estimativa do trabalho do professor para preparar o conteúdo, incluindo seleção de mídias e planejamento. Não é uma medida da dificuldade para o estudante.</li><li><strong>Taxonomia de Bloom:</strong> as indicações são possibilidades, não limites da ferramenta. A exigência cognitiva depende do conteúdo, do enunciado e da tarefa. Criar um material H5P é uma ação do autor; não significa que o estudante mobilizará automaticamente o processo de criar.</li><li><strong>Prática e feedback:</strong> verificar uma resposta pode oferecer apenas indicação de acerto ou erro. Planeje devolutivas que expliquem o raciocínio e ajudem em uma nova tentativa.</li><li><strong>Avaliação e notas:</strong> possibilidade de verificar respostas, relatório de tentativas e registro de nota são aspectos distintos. No Moodle, o acompanhamento depende do tipo de conteúdo, da integração e das configurações da atividade.</li><li><strong>Uso combinado:</strong> uma exploração no H5P pode ser seguida de debate no Fórum ou de produção entregue pela Tarefa.</li><li><strong>Acessibilidade:</strong> confira a interação e a versão utilizada, o acesso pelo teclado, as descrições das imagens e as legendas dos vídeos. As cores deste guia são acompanhadas de símbolos e textos.</li></ol>
<details><summary>Fontes e critérios da proposta</summary><p>Funcionalidades consultadas na <a href="https://h5p.org/content-types-and-applications">documentação oficial do H5P</a> e na <a href="https://docs.moodle.org/501/en/H5P_activity">documentação da atividade H5P no Moodle</a>. A seleção abrange 54 recursos e não representa o catálogo completo. A disponibilidade depende da instalação.</p><p>Os agrupamentos, exemplos, estimativas de facilidade e classificações pedagógicas são uma proposta editorial do guia, não uma classificação oficial do H5P. Data da consulta: 30 de setembro de 2026.</p><p>Referência para a organização em matriz: <a href="https://moodletoolguide.net/pt-br/">Guia de Ferramentas Moodle para Professores e Educadores</a>, disponibilizado por Nicolas Martignoni, baseado na ideia de Joyce Seitzinger, com tradução e adaptação brasileira de Gilvan Marques. Os textos e a matriz deste guia H5P foram elaborados para esta proposta.</p></details></section>
</main><footer class="shell"><p>Guia de Funcionalidades H5P para Professores e Educadores · Proposta inicial · Setembro de 2026.</p><p><a href="https://h5p.org/content-types-and-applications">Catálogo H5P</a> · <a href="https://docs.moodle.org/501/en/H5P_activity">H5P no Moodle</a> · <a href="#conteudo">Voltar ao início</a></p></footer></body></html>`;
await writeFile(new URL('index.html',base),html,'utf8');
console.log(`Gerado ${fileURLToPath(new URL('index.html',base))}: ${groups.reduce((n,g)=>n+g.items.length,0)} recursos.`);
